### ISSUE TITLE
Add "do you want to continue" page

### ISSUE THREAD

**Issue by fynnkroeger** [cschlaffner/PROTzilla2#31]
When the run detail page is loaded with `run/myrun` and `myrun` is saved to disk but is not active (run object in memory in the `active_runs` dict in `ui/runs/views.py`), the user should be asked if they want to continue that run. A example where this is practical is when debugging, you dont want a 404 and having to go back and continue manually, but to always continue the run is also not optimal.

**Comment by henninggaertner** [comment]
Already done with new architecture
