### ISSUE TITLE
Change the order of normalization and log transformation in standard workflow

### ISSUE THREAD

**Issue by hendraet** [cschlaffner/PROTzilla2#535]
## Issue description

Currently, the standard workflow lists the normalisation preprocessing step before the log transform step. It should be the other way around.  
(Otherwise this can lead to negative log intensity values, which is not completely wrong but counterintuitive).

**Comment by henninggaertner** [comment]
I feel like we switched this once already, but can't remember from which configuration. But maybe the change got lost and didn't make it to the dev branch.

**Comment by hendraet** [comment]
I tested it on dev this morning and it wasn't switched :man_shrugging:
