### ISSUE TITLE
BUG: Calculations can be started multiple times

### ISSUE THREAD

**Issue by henninggaertner** [cschlaffner/PROTzilla2#555]
# What is the issue?
While a step is calculating and the spinner is shown, the "Calculate" button can still be activated to start another calculation simultaneously. (on safari browser)

# How to reproduce the issue?
Start a step with a longer calulcation, and press the calculate button twice. 

# What is the expected behavior?
The calculate button should ideally be greyed out and "deactivated" so that it can no longer be pressed.

**Comment by Jonas0000** [comment]
In the current version on dev this shoulden't be possible. Can you explain more detailed on which button this is possible?

**Comment by henninggaertner** [comment]
Currently on dev this does not happen anymore.
On the other hand, I don't see a spinner anymore either. Could be that this changed (and I didn't update my branch with the new changes)
As stated in the issue, this happened on the calculate button.

**Comment by henninggaertner** [comment]
I'll reopen this when it happens again, until then we'll consider this fixed.
