### ISSUE TITLE
Update logging in data preprocessing

### ISSUE THREAD

**Issue by BelanaZ** [cschlaffner/PROTzilla2#83]
Most Data Preprocessing methods do not use logging/Django messages framework yet (see wiki), so Errors and Warnings cannot be shown in the frontend.

**Comment by henninggaertner** [comment]
We added the possibility to raise Errors like such
`raise ValueError("x went wrong")` 
and maintained the possibility to return custom messages with all the various logging levels.
It seems to me that this is what was meant.
